"""empty message

Revision ID: 4d8122a6bb19
Revises: 
Create Date: 2023-05-07 20:41:50.112004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d8122a6bb19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    op.drop_table('produit')
    op.drop_table('admin')
    op.drop_table('prix_promo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prix_promo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('prix_promo_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('remise', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('date_debut', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='prix_promo_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('salt', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('iteration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_pkey'),
    sa.UniqueConstraint('username', name='admin_username_key')
    )
    op.create_table('produit',
    sa.Column('id_produit', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('libelle', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prix', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('chemin_image', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prix_promo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categorie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prix_promo_id'], ['prix_promo.id'], name='produit_prix_promo_id_fkey'),
    sa.PrimaryKeyConstraint('id_produit', name='produit_pkey')
    )
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('salt', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('iteration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='client_pkey'),
    sa.UniqueConstraint('username', name='client_username_key')
    )
    # ### end Alembic commands ###
